using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Flos.Generators;

/// <summary>
/// For each IStateSlice annotated with [GenerateDeepClone], generates
/// IDeepCloneable&lt;T&gt; implementation with field-by-field cloning.
/// </summary>
[Generator]
public sealed class DeepCloneGenerator : IIncrementalGenerator
{
    private const string GenerateDeepCloneAttributeShortName = "GenerateDeepClone";
    private const string GenerateDeepCloneAttributeFullName = "Flos.Generators.GenerateDeepCloneAttribute";
    private const string StateSliceInterface = "Flos.Core.State.IStateSlice";
    private const string OrderedMapInterface = "Flos.Collections.IOrderedMap";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("GenerateDeepCloneAttribute.g.cs", """
                // <auto-generated/>
                namespace Flos.Generators
                {
                    [System.AttributeUsage(System.AttributeTargets.Class)]
                    internal sealed class GenerateDeepCloneAttribute : System.Attribute { }
                }
                """);
        });

        var typeInfos = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) =>
                {
                    if (node is not ClassDeclarationSyntax cls || cls.AttributeLists.Count == 0)
                        return false;
                    foreach (var attrList in cls.AttributeLists)
                    {
                        foreach (var attr in attrList.Attributes)
                        {
                            var name = attr.Name.ToString();
                            if (name is "GenerateDeepClone" or "GenerateDeepCloneAttribute"
                                or "Flos.Generators.GenerateDeepClone" or "Flos.Generators.GenerateDeepCloneAttribute")
                                return true;
                        }
                    }
                    return false;
                },
                transform: static (ctx, _) =>
                {
                    var classDecl = (ClassDeclarationSyntax)ctx.Node;
                    var symbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
                    if (symbol is null) return null;

                    return GetDeepCloneInfo(symbol, classDecl.GetLocation());
                })
            .Where(static info => info is not null);

        context.RegisterSourceOutput(typeInfos, static (spc, info) =>
        {
            if (info is null) return;

            if (!info.ImplementsStateSlice)
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    GeneratorDiagnostics.InvalidDeepCloneTarget,
                    info.Location,
                    info.TypeName));
                return;
            }

            foreach (var prop in info.Properties)
            {
                if (prop.Strategy == CloneStrategy.Error)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(
                        GeneratorDiagnostics.NonCloneableField,
                        info.Location,
                        prop.Name, prop.TypeName, info.TypeName));
                    return;
                }
            }

            var source = GenerateDeepCloneSource(info);
            spc.AddSource($"{info.TypeName}.DeepClone.g.cs", source);
        });
    }

    private static DeepCloneInfo GetDeepCloneInfo(INamedTypeSymbol symbol, Location location)
    {
        var implementsStateSlice = symbol.AllInterfaces.Any(
            i => i.ToDisplayString() == StateSliceInterface);

        var properties = new System.Collections.Generic.List<PropertyCloneInfo>();

        foreach (var member in symbol.GetMembers())
        {
            if (member is not IPropertySymbol prop) continue;
            if (prop.IsStatic || prop.IsReadOnly || prop.SetMethod is null) continue;
            if (prop.DeclaredAccessibility is not (Accessibility.Public or Accessibility.Internal)) continue;

            var strategy = ClassifyField(prop.Type);
            properties.Add(new PropertyCloneInfo(
                prop.Name,
                prop.Type.ToDisplayString(),
                strategy,
                GetOrderedMapKeyType(prop.Type),
                GetOrderedMapValueType(prop.Type)));
        }

        return new DeepCloneInfo(
            symbol.Name,
            symbol.ToDisplayString(),
            symbol.ContainingNamespace?.ToDisplayString() ?? "",
            implementsStateSlice,
            properties.ToArray(),
            location);
    }

    private static CloneStrategy ClassifyField(ITypeSymbol type)
    {
        if (type.IsValueType) return CloneStrategy.DirectCopy;
        if (type.SpecialType == SpecialType.System_String) return CloneStrategy.DirectCopy;

        if (ImplementsOrderedMap(type))
            return CloneStrategy.OrderedMapCopy;

        if (ImplementsDeepCloneable(type))
            return CloneStrategy.DeepClone;

        return CloneStrategy.Error;
    }

    private static bool ImplementsOrderedMap(ITypeSymbol type)
    {
        foreach (var iface in type.AllInterfaces)
        {
            if (iface.OriginalDefinition.ContainingNamespace?.ToDisplayString() == "Flos.Collections"
                && iface.OriginalDefinition.Name == "IOrderedMap")
                return true;
        }
        if (type is INamedTypeSymbol named
            && named.OriginalDefinition.ContainingNamespace?.ToDisplayString() == "Flos.Collections"
            && named.OriginalDefinition.Name == "IOrderedMap")
            return true;
        return false;
    }

    private static bool ImplementsDeepCloneable(ITypeSymbol type)
    {
        foreach (var iface in type.AllInterfaces)
        {
            if (iface.OriginalDefinition.ContainingNamespace?.ToDisplayString() == "Flos.Snapshot"
                && iface.OriginalDefinition.Name == "IDeepCloneable")
                return true;
        }
        return false;
    }

    private static string? GetOrderedMapKeyType(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol named
            && named.OriginalDefinition.ContainingNamespace?.ToDisplayString() == "Flos.Collections"
            && named.OriginalDefinition.Name == "IOrderedMap"
            && named.TypeArguments.Length == 2)
            return named.TypeArguments[0].ToDisplayString();

        foreach (var iface in type.AllInterfaces)
        {
            if (iface.OriginalDefinition.ContainingNamespace?.ToDisplayString() == "Flos.Collections"
                && iface.OriginalDefinition.Name == "IOrderedMap"
                && iface.TypeArguments.Length == 2)
                return iface.TypeArguments[0].ToDisplayString();
        }
        return null;
    }

    private static string? GetOrderedMapValueType(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol named
            && named.OriginalDefinition.ContainingNamespace?.ToDisplayString() == "Flos.Collections"
            && named.OriginalDefinition.Name == "IOrderedMap"
            && named.TypeArguments.Length == 2)
            return named.TypeArguments[1].ToDisplayString();

        foreach (var iface in type.AllInterfaces)
        {
            if (iface.OriginalDefinition.ContainingNamespace?.ToDisplayString() == "Flos.Collections"
                && iface.OriginalDefinition.Name == "IOrderedMap"
                && iface.TypeArguments.Length == 2)
                return iface.TypeArguments[1].ToDisplayString();
        }
        return null;
    }

    private static string GenerateDeepCloneSource(DeepCloneInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");

        if (!string.IsNullOrEmpty(info.Namespace))
        {
            sb.AppendLine($"namespace {info.Namespace}");
            sb.AppendLine("{");
        }

        sb.AppendLine($"    partial class {info.TypeName} : Flos.Snapshot.IDeepCloneable<{info.TypeName}>");
        sb.AppendLine("    {");
        sb.AppendLine($"        public {info.TypeName} DeepClone()");
        sb.AppendLine("        {");
        sb.AppendLine($"            var clone = new {info.TypeName}();");

        foreach (var prop in info.Properties)
        {
            switch (prop.Strategy)
            {
                case CloneStrategy.DirectCopy:
                    sb.AppendLine($"            clone.{prop.Name} = this.{prop.Name};");
                    break;

                case CloneStrategy.OrderedMapCopy:
                    var varName = $"__{prop.Name}Clone";
                    sb.AppendLine($"            var {varName} = new Flos.Collections.SortedArrayMap<{prop.KeyType}, {prop.ValueType}>();");
                    sb.AppendLine($"            foreach (var kvp in this.{prop.Name}) {varName}.Add(kvp.Key, kvp.Value);");
                    sb.AppendLine($"            clone.{prop.Name} = {varName};");
                    break;

                case CloneStrategy.DeepClone:
                    sb.AppendLine($"            clone.{prop.Name} = this.{prop.Name}?.DeepClone();");
                    break;
            }
        }

        sb.AppendLine("            return clone;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        if (!string.IsNullOrEmpty(info.Namespace))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }
}

internal enum CloneStrategy
{
    DirectCopy,
    OrderedMapCopy,
    DeepClone,
    Error
}

internal sealed record PropertyCloneInfo(
    string Name,
    string TypeName,
    CloneStrategy Strategy,
    string? KeyType,
    string? ValueType) : System.IEquatable<PropertyCloneInfo>;

internal sealed record DeepCloneInfo(
    string TypeName,
    string FullTypeName,
    string Namespace,
    bool ImplementsStateSlice,
    PropertyCloneInfo[] Properties,
    Location? Location) : System.IEquatable<DeepCloneInfo>
{
    public bool Equals(DeepCloneInfo? other)
    {
        if (other is null) return false;
        if (TypeName != other.TypeName) return false;
        if (FullTypeName != other.FullTypeName) return false;
        if (Namespace != other.Namespace) return false;
        if (ImplementsStateSlice != other.ImplementsStateSlice) return false;
        if (Properties.Length != other.Properties.Length) return false;
        for (int i = 0; i < Properties.Length; i++)
        {
            if (!Properties[i].Equals(other.Properties[i])) return false;
        }
        return true;
    }

    public override int GetHashCode()
    {
        unchecked
        {
            int hash = 17;
            hash = hash * 31 + TypeName.GetHashCode();
            hash = hash * 31 + FullTypeName.GetHashCode();
            return hash;
        }
    }
}
