using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Flos.Generators;

/// <summary>
/// For each IStateSlice annotated with [DeepClone], generates
/// IDeepCloneable&lt;T&gt; implementation with field-by-field cloning.
/// </summary>
[Generator]
public sealed class DeepCloneGenerator : IIncrementalGenerator
{
    private const string AttributeShortName = "DeepClone";
    private const string AttributeFullName = "Flos.Generators.DeepCloneAttribute";
    private const string StateSliceInterface = "Flos.Core.State.IStateSlice";
    private const string OrderedMapInterface = "Flos.Collections.IOrderedMap";
    private const string OrderedSetInterface = "Flos.Collections.IOrderedSet";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("DeepCloneAttribute.g.cs", """
                // <auto-generated/>
                namespace Flos.Generators
                {
                    [System.AttributeUsage(System.AttributeTargets.Class)]
                    internal sealed class DeepCloneAttribute : System.Attribute { }
                }
                """);
        });

        var typeInfos = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) =>
                {
                    if (node is not ClassDeclarationSyntax cls || cls.AttributeLists.Count == 0)
                        return false;
                    foreach (var attrList in cls.AttributeLists)
                    {
                        foreach (var attr in attrList.Attributes)
                        {
                            var name = attr.Name.ToString();
                            if (name is "DeepClone" or "DeepCloneAttribute"
                                or "Flos.Generators.DeepClone" or "Flos.Generators.DeepCloneAttribute")
                                return true;
                        }
                    }
                    return false;
                },
                transform: static (ctx, _) =>
                {
                    var classDecl = (ClassDeclarationSyntax)ctx.Node;
                    var symbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
                    if (symbol is null) return null;

                    return GetDeepCloneInfo(symbol);
                })
            .Where(static info => info is not null);

        context.RegisterSourceOutput(typeInfos, static (spc, info) =>
        {
            if (info is null) return;

            if (!info.ImplementsStateSlice)
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    GeneratorDiagnostics.InvalidDeepCloneTarget,
                    Location.None,
                    info.TypeName));
                return;
            }

            foreach (var prop in info.Properties)
            {
                if (prop.Strategy == CloneStrategy.Error)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(
                        GeneratorDiagnostics.NonCloneableField,
                        Location.None,
                        prop.Name, prop.TypeName, info.TypeName));
                    return;
                }
            }

            var source = GenerateDeepCloneSource(info);
            spc.AddSource($"{info.TypeName}.DeepClone.g.cs", source);
        });
    }

    private static DeepCloneInfo GetDeepCloneInfo(INamedTypeSymbol symbol)
    {
        var implementsStateSlice = symbol.AllInterfaces.Any(
            i => i.ToDisplayString() == StateSliceInterface);

        var properties = new System.Collections.Generic.List<PropertyCloneInfo>();

        foreach (var member in symbol.GetMembers())
        {
            if (member is IPropertySymbol prop)
            {
                if (prop.IsStatic || prop.IsReadOnly || prop.SetMethod is null) continue;
                if (prop.IsImplicitlyDeclared) continue;

                var strategy = ClassifyField(prop.Type);
                properties.Add(CreatePropertyCloneInfo(prop.Name, prop.Type, strategy));
            }
            else if (member is IFieldSymbol field)
            {
                if (field.IsStatic || field.IsReadOnly || field.IsConst) continue;
                if (field.IsImplicitlyDeclared) continue;

                var strategy = ClassifyField(field.Type);
                properties.Add(CreatePropertyCloneInfo(field.Name, field.Type, strategy));
            }
        }

        return new DeepCloneInfo(
            symbol.Name,
            symbol.ToDisplayString(),
            symbol.ContainingNamespace?.ToDisplayString() ?? "",
            implementsStateSlice,
            properties.ToArray());
    }

    private static PropertyCloneInfo CreatePropertyCloneInfo(string name, ITypeSymbol type, CloneStrategy strategy)
    {
        string? keyType = null;
        string? valueType = null;
        string? elementType = null;
        string? concreteType = null;

        switch (strategy)
        {
            case CloneStrategy.OrderedMapCopy:
            case CloneStrategy.OrderedMapDeepClone:
                keyType = GetOrderedMapKeyType(type);
                valueType = GetOrderedMapValueType(type);
                concreteType = GetOrderedCollectionConcreteType(type, "IOrderedMap");
                break;

            case CloneStrategy.OrderedSetCopy:
                elementType = GetOrderedSetElementType(type)?.ToDisplayString();
                concreteType = GetOrderedCollectionConcreteType(type, "IOrderedSet");
                break;

            case CloneStrategy.ListCopy:
            case CloneStrategy.ListDeepClone:
                elementType = GetListElementType(type)?.ToDisplayString();
                break;

            case CloneStrategy.ArrayCopy:
            case CloneStrategy.ArrayDeepClone:
                elementType = (type as IArrayTypeSymbol)?.ElementType.ToDisplayString();
                break;

            case CloneStrategy.DictionaryCopy:
            case CloneStrategy.DictionaryDeepClone:
                var (k, v) = GetDictionaryTypeArgs(type);
                keyType = k?.ToDisplayString();
                valueType = v?.ToDisplayString();
                break;

            case CloneStrategy.HashSetCopy:
                elementType = GetHashSetElementType(type)?.ToDisplayString();
                break;
        }

        return new PropertyCloneInfo(
            name,
            type.ToDisplayString(),
            strategy,
            keyType,
            valueType,
            elementType,
            concreteType);
    }

    private static string GetOrderedCollectionConcreteType(ITypeSymbol type, string interfaceName)
    {
        // If the field is declared as a concrete type (SortedArrayMap, OrderedMap, etc.), use it
        if (type is INamedTypeSymbol named && named.ContainingNamespace?.ToDisplayString() == "Flos.Collections")
        {
            var typeName = named.OriginalDefinition.Name;
            if (typeName != interfaceName) // Not the interface itself
                return named.ToDisplayString();
        }
        // Default: use SortedArrayMap/SortedArraySet for interface-typed fields
        return null!;
    }

    private static CloneStrategy ClassifyField(ITypeSymbol type)
    {
        if (type.IsValueType) return CloneStrategy.DirectCopy;
        if (type.SpecialType == SpecialType.System_String) return CloneStrategy.DirectCopy;

        if (type is IArrayTypeSymbol arrayType)
        {
            var elemType = arrayType.ElementType;
            if (elemType.IsValueType || elemType.SpecialType == SpecialType.System_String)
                return CloneStrategy.ArrayCopy;
            if (ImplementsDeepCloneable(elemType))
                return CloneStrategy.ArrayDeepClone;
            return CloneStrategy.Error;
        }

        if (ImplementsOrderedMap(type))
        {
            var valueTypeSymbol = GetOrderedMapValueTypeSymbol(type);
            if (valueTypeSymbol is not null && !valueTypeSymbol.IsValueType && valueTypeSymbol.SpecialType != SpecialType.System_String)
            {
                if (ImplementsDeepCloneable(valueTypeSymbol))
                    return CloneStrategy.OrderedMapDeepClone;
                return CloneStrategy.Error;
            }
            return CloneStrategy.OrderedMapCopy;
        }

        if (ImplementsOrderedSet(type))
        {
            return CloneStrategy.OrderedSetCopy;
        }

        var listElem = GetListElementType(type);
        if (listElem is not null)
        {
            if (listElem.IsValueType || listElem.SpecialType == SpecialType.System_String)
                return CloneStrategy.ListCopy;
            if (ImplementsDeepCloneable(listElem))
                return CloneStrategy.ListDeepClone;
            return CloneStrategy.Error;
        }

        var (dictKey, dictValue) = GetDictionaryTypeArgs(type);
        if (dictKey is not null && dictValue is not null)
        {
            if (dictValue.IsValueType || dictValue.SpecialType == SpecialType.System_String)
                return CloneStrategy.DictionaryCopy;
            if (ImplementsDeepCloneable(dictValue))
                return CloneStrategy.DictionaryDeepClone;
            return CloneStrategy.Error;
        }

        var hashSetElem = GetHashSetElementType(type);
        if (hashSetElem is not null)
        {
            if (hashSetElem.IsValueType || hashSetElem.SpecialType == SpecialType.System_String)
                return CloneStrategy.HashSetCopy;
            return CloneStrategy.Error;
        }

        if (ImplementsDeepCloneable(type))
            return CloneStrategy.DeepClone;

        return CloneStrategy.Error;
    }

    private static bool ImplementsOrderedMap(ITypeSymbol type)
    {
        foreach (var iface in type.AllInterfaces)
        {
            if (iface.OriginalDefinition.ContainingNamespace?.ToDisplayString() == "Flos.Collections"
                && iface.OriginalDefinition.Name == "IOrderedMap")
                return true;
        }
        if (type is INamedTypeSymbol named
            && named.OriginalDefinition.ContainingNamespace?.ToDisplayString() == "Flos.Collections"
            && named.OriginalDefinition.Name == "IOrderedMap")
            return true;
        return false;
    }

    private static bool ImplementsOrderedSet(ITypeSymbol type)
    {
        foreach (var iface in type.AllInterfaces)
        {
            if (iface.OriginalDefinition.ContainingNamespace?.ToDisplayString() == "Flos.Collections"
                && iface.OriginalDefinition.Name == "IOrderedSet")
                return true;
        }
        if (type is INamedTypeSymbol named
            && named.OriginalDefinition.ContainingNamespace?.ToDisplayString() == "Flos.Collections"
            && named.OriginalDefinition.Name == "IOrderedSet")
            return true;
        return false;
    }

    private static ITypeSymbol? GetOrderedSetElementType(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol named
            && named.OriginalDefinition.ContainingNamespace?.ToDisplayString() == "Flos.Collections"
            && named.OriginalDefinition.Name == "IOrderedSet"
            && named.TypeArguments.Length == 1)
            return named.TypeArguments[0];

        foreach (var iface in type.AllInterfaces)
        {
            if (iface.OriginalDefinition.ContainingNamespace?.ToDisplayString() == "Flos.Collections"
                && iface.OriginalDefinition.Name == "IOrderedSet"
                && iface.TypeArguments.Length == 1)
                return iface.TypeArguments[0];
        }
        return null;
    }

    private static bool ImplementsDeepCloneable(ITypeSymbol type)
    {
        foreach (var iface in type.AllInterfaces)
        {
            var ns = iface.OriginalDefinition.ContainingNamespace?.ToDisplayString();
            if ((ns == "Flos.Core.State" || ns == "Flos.Pattern.CQRS")
                && iface.OriginalDefinition.Name == "IDeepCloneable")
                return true;
        }
        return false;
    }

    private static ITypeSymbol? GetListElementType(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol named
            && named.OriginalDefinition.SpecialType == SpecialType.None
            && named.OriginalDefinition.ToDisplayString() == "System.Collections.Generic.List<T>"
            && named.TypeArguments.Length == 1)
            return named.TypeArguments[0];

        return null;
    }

    private static (ITypeSymbol? Key, ITypeSymbol? Value) GetDictionaryTypeArgs(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol named
            && named.OriginalDefinition.ToDisplayString() == "System.Collections.Generic.Dictionary<TKey, TValue>"
            && named.TypeArguments.Length == 2)
            return (named.TypeArguments[0], named.TypeArguments[1]);

        return (null, null);
    }

    private static ITypeSymbol? GetHashSetElementType(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol named
            && named.OriginalDefinition.ToDisplayString() == "System.Collections.Generic.HashSet<T>"
            && named.TypeArguments.Length == 1)
            return named.TypeArguments[0];

        return null;
    }

    private static string? GetOrderedMapKeyType(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol named
            && named.OriginalDefinition.ContainingNamespace?.ToDisplayString() == "Flos.Collections"
            && named.OriginalDefinition.Name == "IOrderedMap"
            && named.TypeArguments.Length == 2)
            return named.TypeArguments[0].ToDisplayString();

        foreach (var iface in type.AllInterfaces)
        {
            if (iface.OriginalDefinition.ContainingNamespace?.ToDisplayString() == "Flos.Collections"
                && iface.OriginalDefinition.Name == "IOrderedMap"
                && iface.TypeArguments.Length == 2)
                return iface.TypeArguments[0].ToDisplayString();
        }
        return null;
    }

    private static string? GetOrderedMapValueType(ITypeSymbol type)
    {
        var symbol = GetOrderedMapValueTypeSymbol(type);
        return symbol?.ToDisplayString();
    }

    private static ITypeSymbol? GetOrderedMapValueTypeSymbol(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol named
            && named.OriginalDefinition.ContainingNamespace?.ToDisplayString() == "Flos.Collections"
            && named.OriginalDefinition.Name == "IOrderedMap"
            && named.TypeArguments.Length == 2)
            return named.TypeArguments[1];

        foreach (var iface in type.AllInterfaces)
        {
            if (iface.OriginalDefinition.ContainingNamespace?.ToDisplayString() == "Flos.Collections"
                && iface.OriginalDefinition.Name == "IOrderedMap"
                && iface.TypeArguments.Length == 2)
                return iface.TypeArguments[1];
        }
        return null;
    }

    private static string GenerateDeepCloneSource(DeepCloneInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");

        if (!string.IsNullOrEmpty(info.Namespace))
        {
            sb.AppendLine($"namespace {info.Namespace}");
            sb.AppendLine("{");
        }

        sb.AppendLine($"    partial class {info.TypeName} : Flos.Core.State.IDeepCloneable<{info.TypeName}>");
        sb.AppendLine("    {");
        sb.AppendLine($"        public {info.TypeName} DeepClone()");
        sb.AppendLine("        {");
        sb.AppendLine($"            var clone = new {info.TypeName}();");

        foreach (var prop in info.Properties)
        {
            var v = $"__{prop.Name}Clone";

            switch (prop.Strategy)
            {
                case CloneStrategy.DirectCopy:
                    sb.AppendLine($"            clone.{prop.Name} = this.{prop.Name};");
                    break;

                case CloneStrategy.OrderedMapCopy:
                    {
                        var ctor = prop.ConcreteType ?? $"Flos.Collections.SortedArrayMap<{prop.KeyType}, {prop.ValueType}>";
                        sb.AppendLine($"            if (this.{prop.Name} is not null)");
                        sb.AppendLine($"            {{");
                        sb.AppendLine($"                var {v} = new {ctor}();");
                        sb.AppendLine($"                foreach (var kvp in this.{prop.Name}) {v}.Add(kvp.Key, kvp.Value);");
                        sb.AppendLine($"                clone.{prop.Name} = {v};");
                        sb.AppendLine($"            }}");
                    }
                    break;

                case CloneStrategy.OrderedMapDeepClone:
                    {
                        var ctor = prop.ConcreteType ?? $"Flos.Collections.SortedArrayMap<{prop.KeyType}, {prop.ValueType}>";
                        sb.AppendLine($"            if (this.{prop.Name} is not null)");
                        sb.AppendLine($"            {{");
                        sb.AppendLine($"                var {v} = new {ctor}();");
                        sb.AppendLine($"                foreach (var kvp in this.{prop.Name}) {v}.Add(kvp.Key, kvp.Value.DeepClone());");
                        sb.AppendLine($"                clone.{prop.Name} = {v};");
                        sb.AppendLine($"            }}");
                    }
                    break;

                case CloneStrategy.OrderedSetCopy:
                    {
                        var ctor = prop.ConcreteType ?? $"Flos.Collections.SortedArraySet<{prop.ElementType}>";
                        sb.AppendLine($"            if (this.{prop.Name} is not null)");
                        sb.AppendLine($"            {{");
                        sb.AppendLine($"                var {v} = new {ctor}();");
                        sb.AppendLine($"                foreach (var item in this.{prop.Name}) {v}.Add(item);");
                        sb.AppendLine($"                clone.{prop.Name} = {v};");
                        sb.AppendLine($"            }}");
                    }
                    break;

                case CloneStrategy.DeepClone:
                    sb.AppendLine($"            clone.{prop.Name} = this.{prop.Name}?.DeepClone();");
                    break;

                case CloneStrategy.ArrayCopy:
                    sb.AppendLine($"            clone.{prop.Name} = this.{prop.Name} is not null ? ({prop.TypeName})this.{prop.Name}.Clone() : null;");
                    break;

                case CloneStrategy.ArrayDeepClone:
                    sb.AppendLine($"            if (this.{prop.Name} is not null)");
                    sb.AppendLine($"            {{");
                    sb.AppendLine($"                var {v} = new {prop.ElementType}[this.{prop.Name}.Length];");
                    sb.AppendLine($"                for (int i = 0; i < this.{prop.Name}.Length; i++) {v}[i] = this.{prop.Name}[i].DeepClone();");
                    sb.AppendLine($"                clone.{prop.Name} = {v};");
                    sb.AppendLine($"            }}");
                    break;

                case CloneStrategy.ListCopy:
                    sb.AppendLine($"            clone.{prop.Name} = this.{prop.Name} is not null ? new System.Collections.Generic.List<{prop.ElementType}>(this.{prop.Name}) : null;");
                    break;

                case CloneStrategy.ListDeepClone:
                    sb.AppendLine($"            if (this.{prop.Name} is not null)");
                    sb.AppendLine($"            {{");
                    sb.AppendLine($"                var {v} = new System.Collections.Generic.List<{prop.ElementType}>(this.{prop.Name}.Count);");
                    sb.AppendLine($"                foreach (var item in this.{prop.Name}) {v}.Add(item.DeepClone());");
                    sb.AppendLine($"                clone.{prop.Name} = {v};");
                    sb.AppendLine($"            }}");
                    break;

                case CloneStrategy.DictionaryCopy:
                    sb.AppendLine($"            clone.{prop.Name} = this.{prop.Name} is not null ? new System.Collections.Generic.Dictionary<{prop.KeyType}, {prop.ValueType}>(this.{prop.Name}) : null;");
                    break;

                case CloneStrategy.DictionaryDeepClone:
                    sb.AppendLine($"            if (this.{prop.Name} is not null)");
                    sb.AppendLine($"            {{");
                    sb.AppendLine($"                var {v} = new System.Collections.Generic.Dictionary<{prop.KeyType}, {prop.ValueType}>(this.{prop.Name}.Count);");
                    sb.AppendLine($"                foreach (var kvp in this.{prop.Name}) {v}[kvp.Key] = kvp.Value.DeepClone();");
                    sb.AppendLine($"                clone.{prop.Name} = {v};");
                    sb.AppendLine($"            }}");
                    break;

                case CloneStrategy.HashSetCopy:
                    sb.AppendLine($"            clone.{prop.Name} = this.{prop.Name} is not null ? new System.Collections.Generic.HashSet<{prop.ElementType}>(this.{prop.Name}) : null;");
                    break;
            }
        }

        sb.AppendLine("            return clone;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        if (!string.IsNullOrEmpty(info.Namespace))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }
}

internal enum CloneStrategy
{
    DirectCopy,
    OrderedMapCopy,
    OrderedMapDeepClone,
    OrderedSetCopy,
    DeepClone,
    ArrayCopy,
    ArrayDeepClone,
    ListCopy,
    ListDeepClone,
    DictionaryCopy,
    DictionaryDeepClone,
    HashSetCopy,
    Error
}

internal sealed record PropertyCloneInfo(
    string Name,
    string TypeName,
    CloneStrategy Strategy,
    string? KeyType,
    string? ValueType,
    string? ElementType,
    string? ConcreteType);

internal sealed record DeepCloneInfo(
    string TypeName,
    string FullTypeName,
    string Namespace,
    bool ImplementsStateSlice,
    PropertyCloneInfo[] Properties)
{
    public bool Equals(DeepCloneInfo? other)
    {
        if (other is null) return false;
        if (TypeName != other.TypeName) return false;
        if (FullTypeName != other.FullTypeName) return false;
        if (Namespace != other.Namespace) return false;
        if (ImplementsStateSlice != other.ImplementsStateSlice) return false;
        if (Properties.Length != other.Properties.Length) return false;
        for (int i = 0; i < Properties.Length; i++)
        {
            if (!Properties[i].Equals(other.Properties[i])) return false;
        }
        return true;
    }

    public override int GetHashCode()
    {
        unchecked
        {
            int hash = 17;
            hash = hash * 31 + TypeName.GetHashCode();
            hash = hash * 31 + FullTypeName.GetHashCode();
            return hash;
        }
    }
}
