using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Flos.Generators;

/// <summary>
/// Scans for types marked with <c>[AutoRegister]</c> that implement
/// <c>ICommandHandler&lt;T&gt;</c> or <c>IEventApplier&lt;TEvent, TState&gt;</c>.
/// Generates a static FlosRegistration class with RegisterAll(IHandlerRegistry).
/// <para>
/// Types without <c>[AutoRegister]</c> are not included — they must be
/// registered manually, which allows constructor parameters and custom wiring.
/// </para>
/// Event types implementing <c>IEvent</c> are still auto-discovered (no attribute needed).
/// </summary>
[Generator]
public sealed class RegistrationGenerator : IIncrementalGenerator
{
    private const string AttributeShortName = "AutoRegister";
    private const string AttributeFullName = "Flos.Generators.AutoRegisterAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("AutoRegisterAttribute.g.cs", """
                // <auto-generated/>
                namespace Flos.Generators
                {
                    /// <summary>
                    /// Marks a handler or applier for auto-registration in the generated
                    /// <c>FlosRegistration.RegisterAll()</c> method. The type must have a
                    /// parameterless constructor. Types without this attribute must be
                    /// registered manually, which allows constructor injection.
                    /// </summary>
                    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct)]
                    internal sealed class AutoRegisterAttribute : System.Attribute { }
                }
                """);
        });

        var registrationInfos = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) =>
                {
                    // Fast check: only look at types with base lists and at least one attribute
                    if (node is ClassDeclarationSyntax cls)
                        return cls.BaseList is not null;
                    if (node is StructDeclarationSyntax str)
                        return str.BaseList is not null;
                    if (node is RecordDeclarationSyntax rec)
                        return rec.BaseList is not null;
                    return false;
                },
                transform: static (ctx, _) => GetRegistrationInfos(ctx))
            .Where(static infos => infos.Length > 0)
            .SelectMany(static (infos, _) => infos);

        var collected = registrationInfos.Collect();

        context.RegisterSourceOutput(collected, static (spc, infos) =>
        {
            var all = infos.ToArray();

            if (all.Length == 0)
                return;

            var handlersAndAppliers = all.Where(i => i.Kind is RegistrationKind.Handler or RegistrationKind.Applier).ToArray();
            var eventTypes = all.Where(i => i.Kind == RegistrationKind.EventType).ToArray();

            foreach (var handler in handlersAndAppliers)
            {
                if (!handler.HasParameterlessConstructor)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(
                        GeneratorDiagnostics.MissingParameterlessConstructor,
                        Location.None,
                        handler.TypeName));
                }
            }

            var validHandlers = handlersAndAppliers.Where(h => h.HasParameterlessConstructor).ToArray();

            if (validHandlers.Length == 0 && eventTypes.Length == 0)
                return;

            var allForNamespace = validHandlers.Length > 0 ? validHandlers : eventTypes;
            var ns = ComputeCommonNamespace(allForNamespace);
            var source = GenerateRegistrationSource(validHandlers, eventTypes, ns);
            spc.AddSource("FlosRegistration.g.cs", source);
        });
    }

    private static ImmutableArray<RegistrationInfo> GetRegistrationInfos(GeneratorSyntaxContext context)
    {
        var symbol = context.SemanticModel.GetDeclaredSymbol(context.Node) as INamedTypeSymbol;
        if (symbol is null || symbol.IsAbstract)
            return ImmutableArray<RegistrationInfo>.Empty;

        var builder = ImmutableArray.CreateBuilder<RegistrationInfo>();
        var location = context.Node.GetLocation();
        var filePath = location.SourceTree?.FilePath;
        var spanStart = location.SourceSpan.Start;
        var spanEnd = location.SourceSpan.End;
        var typeDisplay = symbol.ToDisplayString();
        var containingNs = symbol.ContainingNamespace?.ToDisplayString() ?? "";
        bool hasParameterlessCtor = HasParameterlessConstructor(symbol);
        bool hasEvent = false;
        bool hasAttribute = HasGenerateRegistrationAttributeSyntax(context.Node)
            || HasGenerateRegistrationAttribute(symbol);

        foreach (var iface in symbol.AllInterfaces)
        {
            var original = iface.OriginalDefinition;
            var ns = original.ContainingNamespace?.ToDisplayString() ?? "";
            var name = original.Name;

            if (hasAttribute && ns == "Flos.Pattern.CQRS" && name == "ICommandHandler" && original.Arity == 1)
            {
                var cmdType = iface.TypeArguments[0].ToDisplayString();
                builder.Add(new RegistrationInfo(
                    typeDisplay, containingNs, RegistrationKind.Handler,
                    cmdType, null, hasParameterlessCtor,
                    filePath, spanStart, spanEnd));
            }
            else if (hasAttribute && ns == "Flos.Pattern.CQRS" && name == "IEventApplier" && original.Arity == 2)
            {
                var eventType = iface.TypeArguments[0].ToDisplayString();
                var stateType = iface.TypeArguments[1].ToDisplayString();
                builder.Add(new RegistrationInfo(
                    typeDisplay, containingNs, RegistrationKind.Applier,
                    eventType, stateType, hasParameterlessCtor,
                    filePath, spanStart, spanEnd));
            }
            else if (ns == "Flos.Pattern.CQRS" && name == "IEvent" && original.Arity == 0)
            {
                hasEvent = true;
            }
        }

        if (hasEvent)
        {
            builder.Add(new RegistrationInfo(
                typeDisplay, containingNs, RegistrationKind.EventType,
                typeDisplay, null, true,
                filePath, spanStart, spanEnd));
        }

        return builder.ToImmutable();
    }

    private static bool HasGenerateRegistrationAttribute(INamedTypeSymbol symbol)
    {
        foreach (var attr in symbol.GetAttributes())
        {
            var cls = attr.AttributeClass;
            if (cls is null) continue;

            if (cls.Name == AttributeShortName || cls.Name == AttributeFullName)
                return true;

            var fullName = cls.ToDisplayString();
            if (fullName == AttributeFullName)
                return true;
        }
        return false;
    }

    private static bool HasGenerateRegistrationAttributeSyntax(SyntaxNode node)
    {
        var attrLists = node switch
        {
            ClassDeclarationSyntax cls => cls.AttributeLists,
            StructDeclarationSyntax str => str.AttributeLists,
            RecordDeclarationSyntax rec => rec.AttributeLists,
            _ => default
        };

        foreach (var list in attrLists)
        {
            foreach (var attr in list.Attributes)
            {
                var name = attr.Name.ToString();
                if (name == AttributeShortName || name == AttributeShortName + "Attribute"
                    || name == AttributeFullName || name == "Flos.Generators.AutoRegister")
                    return true;
            }
        }
        return false;
    }

    private static bool HasParameterlessConstructor(INamedTypeSymbol symbol)
    {
        var constructors = symbol.Constructors.Where(c => !c.IsStatic).ToArray();
        if (constructors.Length == 0)
            return true;
        return constructors.Any(c => c.Parameters.Length == 0 && c.DeclaredAccessibility is Accessibility.Public or Accessibility.Internal);
    }

    private static string ComputeCommonNamespace(RegistrationInfo[] infos)
    {
        if (infos.Length == 0) return "";

        var namespaces = infos.Select(i => i.ContainingNamespace).Distinct().ToArray();
        if (namespaces.Length == 1) return namespaces[0];

        var parts = namespaces[0].Split('.');
        int commonLength = parts.Length;

        for (int i = 1; i < namespaces.Length; i++)
        {
            var otherParts = namespaces[i].Split('.');
            int maxLen = System.Math.Min(commonLength, otherParts.Length);
            int j = 0;
            while (j < maxLen && parts[j] == otherParts[j]) j++;
            commonLength = j;
        }

        return commonLength > 0
            ? string.Join(".", parts.Take(commonLength))
            : infos[0].ContainingNamespace;
    }

    private static string GenerateRegistrationSource(RegistrationInfo[] handlers, RegistrationInfo[] eventTypes, string ns)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");

        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }

        sb.AppendLine("    internal static class FlosRegistration");
        sb.AppendLine("    {");
        sb.AppendLine("        internal static void RegisterAll(Flos.Pattern.CQRS.IHandlerRegistry registry)");
        sb.AppendLine("        {");

        foreach (var info in handlers)
        {
            sb.AppendLine($"            registry.Register(new {info.TypeName}());");
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");

        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }
}

internal enum RegistrationKind
{
    Handler,
    Applier,
    EventType
}

internal sealed record RegistrationInfo(
    string TypeName,
    string ContainingNamespace,
    RegistrationKind Kind,
    string PrimaryTypeArg,
    string? SecondaryTypeArg,
    bool HasParameterlessConstructor,
    string? LocationFilePath,
    int LocationSpanStart,
    int LocationSpanEnd)
{
    public bool Equals(RegistrationInfo? other)
    {
        if (other is null) return false;
        return TypeName == other.TypeName
            && ContainingNamespace == other.ContainingNamespace
            && Kind == other.Kind
            && PrimaryTypeArg == other.PrimaryTypeArg
            && SecondaryTypeArg == other.SecondaryTypeArg
            && HasParameterlessConstructor == other.HasParameterlessConstructor;
    }

    public override int GetHashCode()
    {
        unchecked
        {
            int hash = 17;
            hash = hash * 31 + TypeName.GetHashCode();
            hash = hash * 31 + ContainingNamespace.GetHashCode();
            hash = hash * 31 + (int)Kind;
            hash = hash * 31 + PrimaryTypeArg.GetHashCode();
            return hash;
        }
    }
}
