using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Flos.Generators;

/// <summary>
/// Scans for types implementing ICommandHandler&lt;T&gt; and IEventApplier&lt;TEvent, TState&gt;.
/// Generates a static FlosRegistration class with RegisterAll(IHandlerRegistry).
/// </summary>
[Generator]
public sealed class RegistrationGenerator : IIncrementalGenerator
{
    private const string HandlerInterfaceName = "Flos.Pattern.CQRS.ICommandHandler";
    private const string ApplierInterfaceName = "Flos.Pattern.CQRS.IEventApplier";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlerTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetRegistrationInfo(ctx))
            .Where(static info => info is not null);

        var collected = handlerTypes.Collect();

        context.RegisterSourceOutput(collected, static (spc, infos) =>
        {
            var handlers = infos
                .Where(i => i is not null)
                .Select(i => i!)
                .ToArray();

            if (handlers.Length == 0)
                return;

            var ns = handlers[0].ContainingNamespace;
            var source = GenerateRegistrationSource(handlers, ns);
            spc.AddSource("FlosRegistration.g.cs", source);
        });
    }

    private static RegistrationInfo? GetRegistrationInfo(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
        if (symbol is null || symbol.IsAbstract)
            return null;

        foreach (var iface in symbol.AllInterfaces)
        {
            var original = iface.OriginalDefinition;
            var ns = original.ContainingNamespace?.ToDisplayString() ?? "";
            var name = original.Name;

            if (ns == "Flos.Pattern.CQRS" && name == "ICommandHandler" && original.Arity == 1)
            {
                var cmdType = iface.TypeArguments[0].ToDisplayString();
                return new RegistrationInfo(
                    symbol.ToDisplayString(),
                    symbol.ContainingNamespace?.ToDisplayString() ?? "",
                    RegistrationKind.Handler,
                    cmdType,
                    null);
            }

            if (ns == "Flos.Pattern.CQRS" && name == "IEventApplier" && original.Arity == 2)
            {
                var eventType = iface.TypeArguments[0].ToDisplayString();
                var stateType = iface.TypeArguments[1].ToDisplayString();
                return new RegistrationInfo(
                    symbol.ToDisplayString(),
                    symbol.ContainingNamespace?.ToDisplayString() ?? "",
                    RegistrationKind.Applier,
                    eventType,
                    stateType);
            }
        }

        return null;
    }

    private static string GenerateRegistrationSource(RegistrationInfo[] infos, string ns)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");

        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }

        sb.AppendLine("    internal static class FlosRegistration");
        sb.AppendLine("    {");
        sb.AppendLine("        internal static void RegisterAll(Flos.Pattern.CQRS.IHandlerRegistry registry)");
        sb.AppendLine("        {");

        foreach (var info in infos)
        {
            if (info.Kind == RegistrationKind.Handler)
            {
                sb.AppendLine($"            registry.Register(new {info.TypeName}());");
            }
            else
            {
                sb.AppendLine($"            registry.Register(new {info.TypeName}());");
            }
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");

        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }
}

internal enum RegistrationKind
{
    Handler,
    Applier
}

internal sealed record RegistrationInfo(
    string TypeName,
    string ContainingNamespace,
    RegistrationKind Kind,
    string PrimaryTypeArg,
    string? SecondaryTypeArg) : System.IEquatable<RegistrationInfo>;
