using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Flos.Generators;

/// <summary>
/// Scans all IMessage and IStateSlice implementations and generates a static FlosTypeResolver
/// mapping deterministic integer type IDs (FNV-1a hash of full type name) to Type.
/// Hash collisions produce a compile-time error diagnostic.
/// </summary>
[Generator]
public sealed class TypeResolverGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var typeInfos = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax or StructDeclarationSyntax or RecordDeclarationSyntax,
                transform: static (ctx, _) => GetTypeResolverEntry(ctx))
            .Where(static entry => entry is not null);

        var collected = typeInfos.Collect();

        context.RegisterSourceOutput(collected, static (spc, entries) =>
        {
            var validEntries = entries
                .Where(e => e is not null)
                .Select(e => e!)
                .ToArray();

            if (validEntries.Length == 0) return;

            var hashToType = new Dictionary<int, TypeResolverEntry>();
            foreach (var entry in validEntries)
            {
                if (hashToType.TryGetValue(entry.Hash, out var existing))
                {
                    spc.ReportDiagnostic(Diagnostic.Create(
                        GeneratorDiagnostics.HashCollision,
                        Location.None,
                        entry.FullTypeName, existing.FullTypeName, entry.Hash));
                    return;
                }
                hashToType[entry.Hash] = entry;
            }

            var source = GenerateTypeResolverSource(validEntries);
            spc.AddSource("FlosTypeResolver.g.cs", source);
        });
    }

    private static TypeResolverEntry? GetTypeResolverEntry(GeneratorSyntaxContext context)
    {
        var symbol = context.SemanticModel.GetDeclaredSymbol(context.Node) as INamedTypeSymbol;
        if (symbol is null || symbol.IsAbstract) return null;

        bool isMessage = false;
        bool isStateSlice = false;

        foreach (var iface in symbol.AllInterfaces)
        {
            var ns = iface.ContainingNamespace?.ToDisplayString() ?? "";
            var name = iface.Name;

            if (ns == "Flos.Core.Messaging" && name == "IMessage")
                isMessage = true;
            if (ns == "Flos.Core.State" && name == "IStateSlice")
                isStateSlice = true;
        }

        if (!isMessage && !isStateSlice) return null;

        var fullName = symbol.ToDisplayString();
        var hash = HashHelper.ComputeFnv1a(fullName);

        return new TypeResolverEntry(fullName, hash);
    }

    private static string GenerateTypeResolverSource(TypeResolverEntry[] entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace Flos.Generators");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class FlosTypeResolver");
        sb.AppendLine("    {");
        sb.AppendLine("        private static readonly Dictionary<int, Type> IdToType = new()");
        sb.AppendLine("        {");

        foreach (var entry in entries)
        {
            sb.AppendLine($"            {{ {entry.Hash}, typeof({entry.FullTypeName}) }},");
        }

        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("        private static readonly Dictionary<Type, int> TypeToId = new()");
        sb.AppendLine("        {");

        foreach (var entry in entries)
        {
            sb.AppendLine($"            {{ typeof({entry.FullTypeName}), {entry.Hash} }},");
        }

        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("        public static Type? Resolve(int typeId) => IdToType.TryGetValue(typeId, out var type) ? type : null;");
        sb.AppendLine("        public static int? GetId(Type type) => TypeToId.TryGetValue(type, out var id) ? id : null;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}

internal sealed record TypeResolverEntry(string FullTypeName, int Hash) : System.IEquatable<TypeResolverEntry>;
